plugins { 
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android' 
}
android {
    namespace 'com.my.app'
    compileSdk 33

    // 💥 终极解决方案：配置一个万能的专属“本地固定签名”
    signingConfigs {
        release {
            storeFile file("keystore.jks")
            storePassword "123456"
            keyAlias "key0"
            keyPassword "123456"
        }
    }

    defaultConfig {
        applicationId "com.my.app"
        minSdk 26
        targetSdk 30
        versionCode 3 // 顺手把底层版本号升到 3
        versionName "1.0.2" // 表面版本号升到 1.0.2
        resConfigs "zh"
    }
    
    buildTypes {
        debug {
            minifyEnabled false
            shrinkResources false
        }
        // 💥 让正式版使用我们刚才配置的专属签名
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.release
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}
dependencies {
    implementation 'androidx.core:core-ktx:1.10.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
