plugins { 
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android' 
}
android {
    namespace 'com.my.app'
    compileSdk 34 // 适配最新规范

    defaultConfig {
        applicationId "com.my.app"
        minSdk 26
        targetSdk 34 // 解决打包报错的核心
        versionCode 3 
        versionName "1.0.2"
        resConfigs "zh"
    }

    // 屏蔽 Google Play 强制检查机制，防止打包中断报错
    lint {
        checkReleaseBuilds false
        abortOnError false
    }
    
    buildTypes {
        debug {
            minifyEnabled false
            shrinkResources false
        }
        release {
            minifyEnabled false
            shrinkResources false
            // 使用系统通用 debug 签名，免去 JKS 密钥文件烦恼，完美覆盖安装
            signingConfig signingConfigs.debug 
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}
dependencies {
    implementation 'androidx.core:core-ktx:1.10.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
