plugins { 
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android' 
}
android {
    namespace 'com.my.app'
    compileSdk 34 

    // 💥 新增：永久固定签名配置！只要这个在，永远可以覆盖安装！
    signingConfigs {
        release {
            storeFile file("keystore.jks")
            storePassword "123456"
            keyAlias "mykey"
            keyPassword "123456"
        }
    }

    defaultConfig {
        applicationId "com.my.app"
        minSdk 26
        targetSdk 30 
        versionCode 5 
        versionName "1.0.4"
        resConfigs "zh"
    }

    lint {
        checkReleaseBuilds false
        abortOnError false
    }
    
    buildTypes {
        debug {
            minifyEnabled false
            shrinkResources false
        }
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.release // 绑定上面的专属签名
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}
dependencies {
    implementation 'androidx.core:core-ktx:1.10.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
