name: Android Build

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: 

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # 💥 核心修复：强制指定生成稳定版 Gradle 8.4，防止云端自动使用过新的 9.4 导致不兼容崩溃！
    - name: Generate Gradle wrapper
      run: gradle wrapper --gradle-version 8.4

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: 快捷通知-v1.0.2安装包
        path: app/build/outputs/apk/release/app-release.apk
